apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-app-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: my-app-sa  # Le ServiceAccount créé plus tôt
    namespace: default  # Assure-toi que ce soit le bon namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: my-clusterrole  # Le ClusterRole partagé

