apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      serviceAccountName: my-app-sa  # Utilise le ServiceAccount que tu as créé
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

